use std::process::Command;
use std::fs;
use std::path::Path;

fn main() {
    // Get git commit hash
    let git_hash = get_git_hash();

    // Get build date using time crate
    let build_date = get_build_date();

    let epkg_version_info = format!("version {} (build date {}, commit {})",
                                    env!("CARGO_PKG_VERSION"),
                                    build_date,
                                    git_hash);

    // Set environment variables for the build
    println!("cargo:rustc-env=GIT_HASH={}", git_hash);
    println!("cargo:rustc-env=BUILD_DATE={}", build_date);
    println!("cargo:rustc-env=EPKG_VERSION_TAG=v{}", env!("CARGO_PKG_VERSION"));
    println!("cargo:rustc-env=EPKG_VERSION_INFO={}", epkg_version_info);

    // Generate applets module declarations
    generate_applets_modules();
}

fn generate_applets_modules() {
    let applets_dir = Path::new("src/applets");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let registrations_path = Path::new(&out_dir).join("applets_modules.rs");

    let mut modules = Vec::new();
    let mut registrations = Vec::new();

    if let Ok(entries) = fs::read_dir(applets_dir) {
        for entry in entries {
            if let Ok(entry) = entry {
                let path = entry.path();
                if path.is_file() {
                    if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
                        // Skip mod.rs, generated files (starting with _), and any non-Rust files
                        if filename == "mod.rs"
                            || filename.starts_with("_")
                            || !filename.ends_with(".rs") {
                            continue;
                        }

                        // Extract module name (remove .rs extension)
                        let module_name = filename.trim_end_matches(".rs");

                        // Map module name to command name
                        // Convention: if module ends with _cmd, remove it (e.g., true_cmd -> "true")
                        // Convert underscores to hyphens (e.g., dpkg_query -> "dpkg-query")
                        let cmd_name_str = if module_name.ends_with("_cmd") {
                            &module_name[..module_name.len() - 4]
                        } else {
                            module_name
                        };
                        // Convert underscores to hyphens for command names
                        let cmd_name = cmd_name_str.replace('_', "-");

                        modules.push(module_name.to_string());
                        registrations.push((module_name.to_string(), cmd_name.to_string()));
                    }
                }
            }
        }
    }

    // Sort for consistent output
    modules.sort();
    registrations.sort_by(|a, b| a.1.cmp(&b.1));

    // Generate module declarations as a string for mod.rs
    // We'll write this to a file that can be included
    let mut decl_code = String::new();
    decl_code.push_str("// Auto-generated module declarations - do not edit manually\n");
    for module in &modules {
        decl_code.push_str(&format!("pub mod {};\n", module));
    }

    // Generate registrations file
    let mut reg_code = String::new();
    reg_code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    reg_code.push_str("// Auto-register all applets found in src/applets/\n");
    reg_code.push_str("register_applets! {\n");
    for (module, cmd_name) in &registrations {
        reg_code.push_str(&format!("    ({}, \"{}\"),\n", module, cmd_name));
    }
    reg_code.push_str("}\n");

    // Write the generated files
    fs::write(&registrations_path, reg_code).expect("Failed to write generated applets_modules.rs");

    // Write module declarations to src/applets/ - modules must be in the same directory
    // This file is auto-generated and should be in .gitignore
    // Only write if content has changed to avoid unnecessary rebuilds
    let decl_file = applets_dir.join("_modules_gen.rs");
    let should_write = match fs::read_to_string(&decl_file) {
        Ok(existing) => existing != decl_code,
        Err(_) => true, // File doesn't exist, need to create it
    };
    if should_write {
        fs::write(&decl_file, decl_code).expect("Failed to write generated _modules_gen.rs");
    }

    // Tell Cargo to rerun if applets directory changes
    println!("cargo:rerun-if-changed=src/applets");
}

fn get_git_hash() -> String {
    Command::new("git")
        .args(&["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout).ok()
            } else {
                None
            }
        })
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn get_build_date() -> String {
    use time::OffsetDateTime;

    OffsetDateTime::now_utc()
        .format(&time::format_description::parse("[year]-[month]-[day]").unwrap())
        .unwrap_or_else(|_| "unknown".to_string())
}
