format: conda
distro: conda
distro_dirs:
- anaconda
versions:
- "latest"
repos:
  conda-forge:
  pytorch:
  MindSpore:
index_url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/$repo/$conda_arch/$conda_repofile

# Example URLs:
# https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64/current_repodata.json.gz
