use clap::Command;
use color_eyre::Result;
use color_eyre::eyre::eyre;
use color_eyre::eyre::Context;
use std::path::Path;
use std::sync::OnceLock;
use crate::models::PackageFormat;
use crate::utils::force_symlink;
use crate::utils::handle_clap_error_with_cmdline;

// Module declarations - these are auto-generated by build.rs
// To add a new applet, just create the .rs file in this directory
// The build script will automatically discover it and generate the declarations
// This file is generated in src/applets/ so modules can be found
include!("_modules_gen.rs");

/// Macro to register applet commands
/// Auto-generated from applets directory at build time
macro_rules! register_applets {
    ($(($module:ident, $cmd_name:literal)),* $(,)?) => {
        static APPLETS: OnceLock<Vec<Command>> = OnceLock::new();

        /// Get all busybox subcommands
        pub fn busybox_subcommands() -> &'static [Command] {
            APPLETS.get_or_init(|| vec![
                $($module::command(),)*
            ])
        }

        /// Execute a built-in command by name and matches
        /// Returns an error if the command is not a built-in command
        pub fn exec_builtin_command(cmd_name: &str, matches: &clap::ArgMatches) -> Result<()> {
            match cmd_name {
                $(
                    $cmd_name => {
                        let options = $module::parse_options(matches)?;
                        $module::run(options)
                    }
                )*
                _ => {
                    Err(eyre!("Unknown built-in command: {}", cmd_name))
                }
            }
        }
    };
}

// Include auto-generated registrations
// This file is generated by build.rs from files in src/applets/
include!(concat!(env!("OUT_DIR"), "/applets_modules.rs"));

/// Get all applet names sorted alphabetically
pub fn sorted_applet_names() -> Vec<String> {
    let mut names: Vec<String> = busybox_subcommands()
        .iter()
        .map(|cmd| cmd.get_name().to_string())
        .collect();
    names.sort();
    names
}

/// Format applet names into compact lines wrapped at given width
pub fn format_applet_list_compact(width: usize) -> String {
    let names = sorted_applet_names();
    if names.is_empty() {
        return String::new();
    }

    let indent = "    "; // 4 spaces
    let mut result = String::new();
    let mut line = String::new();

    for (i, name) in names.iter().enumerate() {
        let separator = if i == 0 { "" } else { ", " };
        let needed = separator.len() + name.len();

        if line.is_empty() {
            // First applet on a new line
            line.push_str(indent);
            line.push_str(name);
        } else if line.len() + needed <= width {
            // Fits on current line
            line.push_str(separator);
            line.push_str(name);
        } else {
            // Start new line
            result.push_str(&line);
            result.push('\n');
            line.clear();
            line.push_str(indent);
            line.push_str(name);
        }
    }

    if !line.is_empty() {
        result.push_str(&line);
        result.push('\n');
    }

    result
}

/// Extract UID, GID, and mode bits from a reference file
///
/// This is used by chgrp, chmod, and chown applets to implement
/// the `--reference RFILE` flag. Returns an error if the file
/// cannot be accessed or metadata cannot be retrieved.
pub fn extract_reference_metadata(ref_path: &Path) -> Result<(u32, u32, u32)> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        let metadata = std::fs::metadata(ref_path)
            .map_err(|e| eyre!("cannot stat '{}': {}", ref_path.display(), e))?;
        let uid = metadata.uid();
        let gid = metadata.gid();
        let mode = metadata.mode() & 0o7777;
        Ok((uid, gid, mode))
    }
    #[cfg(not(unix))]
    {
        Err(eyre!("--reference not supported on this platform"))
    }
}

/// Get the applet name from the invocation (if any)
/// Returns None if not invoked as an applet
fn get_applet_name_from_invocation() -> Option<String> {
    let args: Vec<String> = std::env::args_os()
        .map(|a| a.to_string_lossy().into_owned())
        .collect();
    if args.is_empty() {
        return None;
    }

    // Get the program name as invoked (first argument)
    let invoked_name = &args[0];

    // Extract basename (handle both "/usr/bin/wget" and "wget")
    let applet_name = std::path::Path::new(invoked_name)
        .file_name()
        .and_then(|n| n.to_str())
        .map(|s| s.to_string());

    let applet_name = match applet_name {
        Some(name) => name,
        None => return None,
    };

    // Don't treat "epkg" itself as an applet
    if applet_name == "epkg" {
        return None;
    }

    Some(applet_name)
}

/// Returns true if the binary was invoked as a registered applet (e.g. symlink named "rpm").
pub fn is_invoked_as_applet() -> bool {
    let invoked = match get_applet_name_from_invocation() {
        Some(name) => name,
        None => return false,
    };
    let (applet_name, _) = if invoked == "[" {
        ("test".to_string(), true)
    } else {
        (invoked, false)
    };
    busybox_subcommands().iter().any(|cmd| cmd.get_name() == applet_name)
}

/// Handle applet invocation - parse arguments and execute the applet
/// Returns Ok(Some(())) if handled as an applet, Ok(None) if not an applet, Err on error
pub fn handle_applet_invocation() -> Result<Option<()>> {
    let invoked_applet_name = match get_applet_name_from_invocation() {
        Some(name) => name,
        None => return Ok(None), // Not invoked as an applet
    };

    // Normalize special invocation aliases.
    //
    // POSIX `[` is typically a synonym for `test` and is invoked as:
    //   [ expression ]
    // so we also strip a trailing `]` argument below.
    let (applet_name, strip_trailing_bracket) = if invoked_applet_name == "[" {
        ("test".to_string(), true)
    } else {
        (invoked_applet_name, false)
    };

    // Handle busybox multicall invocation: busybox <applet> [args...]
    let (applet_name, args_skip) = if applet_name == "busybox" {
        let mut args: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();
        if args.is_empty() {
            // No applet specified, fall back to normal epkg operation
            return Ok(None);
        }
        let real_applet = args.remove(0).to_string_lossy().into_owned();
        (real_applet, 2) // skip both "busybox" and the applet name
    } else {
        (applet_name, 1) // skip only the program name
    };

    // Get all applet commands and find the matching one in a single pass
    let applet_commands = busybox_subcommands();
    let applet_cmd = match applet_commands.iter()
        .find(|cmd| cmd.get_name() == applet_name) {
        Some(cmd) => cmd,
        None => return Ok(None), // Not a valid applet, fall back to normal epkg operation
    };

    // Parse arguments using the applet's command structure.
    // Pass raw OsString so path args (e.g. touch) keep bytes that are not valid UTF-8.
    let mut args: Vec<std::ffi::OsString> = std::env::args_os().skip(args_skip).collect();
    if strip_trailing_bracket && args.last().is_some_and(|a| a == std::ffi::OsStr::new("]")) {
        args.pop();
    }
    args.insert(0, std::ffi::OsString::from(applet_name.as_str()));

    // Try to parse arguments - handle help requests specially
    let cmdline = args.iter().map(|a| a.to_string_lossy()).collect::<Vec<_>>().join(" ");
    let matches = match applet_cmd.clone().try_get_matches_from(args) {
        Ok(matches) => matches,
        Err(e) => handle_clap_error_with_cmdline(e, cmdline),
    };

    // Execute the applet
    exec_builtin_command(&applet_name, &matches)?;

    Ok(Some(()))
}

/// Determine if a command should be placed in sbin (system administration) or bin (user commands)
fn is_sbin_command(cmd_name: &str) -> bool {
    // System administration commands that typically go in /usr/sbin
    let sbin_commands: &[&str] = &[
        "useradd", "userdel", "usermod",
        "groupadd", "groupdel",
        "adduser", "addgroup", "deluser", "delgroup",
    ];
    sbin_commands.contains(&cmd_name)
}

/// Return true when this epkg binary is built for a musl environment.
///
/// All current static builds use musl, so for APK environments we only create
/// applet symlinks when this returns true.
fn is_musl_build() -> bool {
    #[cfg(target_env = "musl")]
    {
        true
    }
    #[cfg(not(target_env = "musl"))]
    {
        false
    }
}

/// Create symlinks for all registered applets in the environment
/// This automatically discovers all applets and places them in the appropriate directory (bin or sbin)
pub fn create_all_applet_symlinks(env_root: &Path, pkg_format: &PackageFormat) -> Result<()> {
    let epkg_exe = std::env::current_exe()
        .with_context(|| "Failed to get current executable path")?;

    // On Alpine (APK format) with a glibc-linked epkg binary, the binary will
    // not run at all. All static builds currently use musl, so only create
    // applet symlinks when building for musl; otherwise return early.
    if *pkg_format == PackageFormat::Apk && !is_musl_build() {
        return Ok(());
    }

    let applet_commands = busybox_subcommands();
    for cmd in applet_commands {
        let cmd_name = cmd.get_name();
        let subdir = if is_sbin_command(cmd_name) { "sbin" } else { "bin" };
        let symlink_path = env_root.join(format!("usr/{}/{}", subdir, cmd_name));
        force_symlink(&epkg_exe, &symlink_path)
            .with_context(|| format!("Failed to create {} symlink in {}", cmd_name, symlink_path.display()))?;
    }
    force_symlink(&epkg_exe, env_root.join("usr/bin/["))?;
    Ok(())
}
