use clap::{Command, error::ErrorKind};
use color_eyre::Result;
use color_eyre::eyre::eyre;
use color_eyre::eyre::Context;
use std::path::Path;
use crate::models::PackageFormat;
use crate::utils::force_symlink;

// Module declarations - these are auto-generated by build.rs
// To add a new applet, just create the .rs file in this directory
// The build script will automatically discover it and generate the declarations
// This file is generated in src/applets/ so modules can be found
include!("_modules_gen.rs");

/// Macro to register applet commands
/// Auto-generated from applets directory at build time
macro_rules! register_applets {
    ($(($module:ident, $cmd_name:literal)),* $(,)?) => {
        /// Get all busybox subcommands
        pub fn busybox_subcommands() -> Vec<Command> {
            vec![
                $($module::command(),)*
            ]
        }

        /// Execute a built-in command by name and matches
        /// Returns an error if the command is not a built-in command
        pub fn exec_builtin_command(cmd_name: &str, matches: &clap::ArgMatches) -> Result<()> {
            match cmd_name {
                $(
                    $cmd_name => {
                        let options = $module::parse_options(matches)?;
                        $module::run(options)
                    }
                )*
                _ => {
                    Err(eyre!("Unknown built-in command: {}", cmd_name))
                }
            }
        }
    };
}

// Include auto-generated registrations
// This file is generated by build.rs from files in src/applets/
include!(concat!(env!("OUT_DIR"), "/applets_modules.rs"));

/// Get the applet name from the invocation (if any)
/// Returns None if not invoked as an applet
fn get_applet_name_from_invocation() -> Option<String> {
    let args: Vec<String> = std::env::args().collect();
    if args.is_empty() {
        return None;
    }

    // Get the program name as invoked (first argument)
    let invoked_name = &args[0];

    // Extract basename (handle both "/usr/bin/wget" and "wget")
    let applet_name = std::path::Path::new(invoked_name)
        .file_name()
        .and_then(|n| n.to_str())
        .map(|s| s.to_string());

    let applet_name = match applet_name {
        Some(name) => name,
        None => return None,
    };

    // Don't treat "epkg" itself as an applet
    if applet_name == "epkg" {
        return None;
    }

    Some(applet_name)
}

/// Handle applet invocation - parse arguments and execute the applet
/// Returns Ok(Some(())) if handled as an applet, Ok(None) if not an applet, Err on error
pub fn handle_applet_invocation() -> Result<Option<()>> {
    let invoked_applet_name = match get_applet_name_from_invocation() {
        Some(name) => name,
        None => return Ok(None), // Not invoked as an applet
    };

    // Normalize special invocation aliases.
    //
    // POSIX `[` is typically a synonym for `test` and is invoked as:
    //   [ expression ]
    // so we also strip a trailing `]` argument below.
    let (applet_name, strip_trailing_bracket) = if invoked_applet_name == "[" {
        ("test".to_string(), true)
    } else {
        (invoked_applet_name, false)
    };

    // Get all applet commands and find the matching one in a single pass
    let applet_commands = busybox_subcommands();
    let applet_cmd = match applet_commands.iter()
        .find(|cmd| cmd.get_name() == applet_name) {
        Some(cmd) => cmd,
        None => return Ok(None), // Not a valid applet, fall back to normal epkg operation
    };

    // Parse arguments using the applet's command structure
    // Clap expects the command name as the first argument, so prepend the applet name
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    if strip_trailing_bracket && args.last().is_some_and(|a| a == "]") {
        args.pop();
    }
    args.insert(0, applet_name.clone());

    // Try to parse arguments - handle help requests specially
    let matches = match applet_cmd.clone().try_get_matches_from(args) {
        Ok(m) => m,
        Err(e) => {
            // If it's a help request or display help error, print it and exit
            if e.kind() == clap::error::ErrorKind::DisplayHelp ||
               e.kind() == clap::error::ErrorKind::DisplayHelpOnMissingArgumentOrSubcommand {
                e.print().expect("Failed to print help");
                std::process::exit(0);
            }
            // For other errors, return them as-is so clap can format them properly
            // Special handling for rpm applet to match system rpm error messages
            // Note: This only applies when invoked directly as "rpm" applet (via symlink),
            // not when invoked via "epkg busybox rpm" where clap errors occur earlier
            if applet_name == "rpm" {
                match e.kind() {
                    ErrorKind::UnknownArgument => {
                        let msg = e.to_string();
                        // Try to extract argument between single quotes
                        let arg = if let Some(start) = msg.find('\'') {
                            if let Some(end) = msg[start+1..].find('\'') {
                                Some(msg[start+1..start+1+end].to_string())
                            } else {
                                None
                            }
                        } else {
                            None
                        };
                        if let Some(arg) = arg {
                            eprintln!("rpm: {}: unknown option", arg);
                        } else {
                            eprintln!("rpm: {}", msg.strip_prefix("error: ").unwrap_or(&msg));
                        }
                    }
                    ErrorKind::MissingRequiredArgument => {
                        eprintln!("rpm: no arguments given for query");
                    }
                    _ => {
                        let msg = e.to_string();
                        if msg.starts_with("error: ") {
                            eprintln!("rpm: {}", &msg[7..]);
                        } else {
                            eprintln!("rpm: {}", msg);
                        }
                    }
                }
                std::process::exit(2);
            } else {
                e.print().expect("Failed to print error");
                std::process::exit(2);
            }
        }
    };

    // Execute the applet
    exec_builtin_command(&applet_name, &matches)?;

    Ok(Some(()))
}

/// Determine if a command should be placed in sbin (system administration) or bin (user commands)
fn is_sbin_command(cmd_name: &str) -> bool {
    // System administration commands that typically go in /usr/sbin
    let sbin_commands: &[&str] = &[
        "useradd", "userdel", "usermod",
        "groupadd", "groupdel",
        "adduser", "addgroup", "deluser", "delgroup",
    ];
    sbin_commands.contains(&cmd_name)
}

/// Return true when this epkg binary is built for a musl environment.
///
/// All current static builds use musl, so for APK environments we only create
/// applet symlinks when this returns true.
fn is_musl_build() -> bool {
    #[cfg(target_env = "musl")]
    {
        true
    }
    #[cfg(not(target_env = "musl"))]
    {
        false
    }
}

/// Create symlinks for all registered applets in the environment
/// This automatically discovers all applets and places them in the appropriate directory (bin or sbin)
pub fn create_all_applet_symlinks(env_root: &Path, pkg_format: &PackageFormat) -> Result<()> {
    let epkg_exe = std::env::current_exe()
        .with_context(|| "Failed to get current executable path")?;

    // On Alpine (APK format) with a glibc-linked epkg binary, the binary will
    // not run at all. All static builds currently use musl, so only create
    // applet symlinks when building for musl; otherwise return early.
    if *pkg_format == PackageFormat::Apk && !is_musl_build() {
        return Ok(());
    }

    let applet_commands = busybox_subcommands();
    for cmd in applet_commands {
        let cmd_name = cmd.get_name();
        let subdir = if is_sbin_command(cmd_name) { "sbin" } else { "bin" };
        let symlink_path = env_root.join(format!("usr/{}/{}", subdir, cmd_name));
        force_symlink(&epkg_exe, &symlink_path)
            .with_context(|| format!("Failed to create {} symlink in {}", cmd_name, symlink_path.display()))?;
    }
    force_symlink(&epkg_exe, env_root.join("usr/bin/["))?;
    Ok(())
}
