use clap::Command;
use color_eyre::Result;
use color_eyre::eyre::eyre;

// Module declarations - these are auto-generated by build.rs
// To add a new applet, just create the .rs file in this directory
// The build script will automatically discover it and generate the declarations
// This file is generated in src/applets/ so modules can be found
include!("_modules_gen.rs");

/// Macro to register applet commands
/// Auto-generated from applets directory at build time
macro_rules! register_applets {
    ($(($module:ident, $cmd_name:literal)),* $(,)?) => {
        /// Get all busybox subcommands
        pub fn busybox_subcommands() -> Vec<Command> {
            vec![
                $($module::command(),)*
            ]
        }

        /// Execute a built-in command by name and matches
        /// Returns an error if the command is not a built-in command
        pub fn exec_builtin_command(cmd_name: &str, matches: &clap::ArgMatches) -> Result<()> {
            match cmd_name {
                $(
                    $cmd_name => {
                        let options = $module::parse_options(matches)?;
                        $module::run(options)
                    }
                )*
                _ => {
                    Err(eyre!("Unknown built-in command: {}", cmd_name))
                }
            }
        }
    };
}

// Include auto-generated registrations
// This file is generated by build.rs from files in src/applets/
include!(concat!(env!("OUT_DIR"), "/applets_modules.rs"));

/// Get the applet name from the invocation (if any)
/// Returns None if not invoked as an applet
fn get_applet_name_from_invocation() -> Option<String> {
    let args: Vec<String> = std::env::args().collect();
    if args.is_empty() {
        return None;
    }

    // Get the program name as invoked (first argument)
    let invoked_name = &args[0];

    // Extract basename (handle both "/usr/bin/wget" and "wget")
    let applet_name = std::path::Path::new(invoked_name)
        .file_name()
        .and_then(|n| n.to_str())
        .map(|s| s.to_string());

    let applet_name = match applet_name {
        Some(name) => name,
        None => return None,
    };

    // Don't treat "epkg" itself as an applet
    if applet_name == "epkg" {
        return None;
    }

    Some(applet_name)
}

/// Handle applet invocation - parse arguments and execute the applet
/// Returns Ok(Some(())) if handled as an applet, Ok(None) if not an applet, Err on error
pub fn handle_applet_invocation() -> Result<Option<()>> {
    let applet_name = match get_applet_name_from_invocation() {
        Some(name) => name,
        None => return Ok(None), // Not invoked as an applet
    };

    // Get all applet commands and find the matching one in a single pass
    let applet_commands = busybox_subcommands();
    let applet_cmd = match applet_commands.iter()
        .find(|cmd| cmd.get_name() == applet_name) {
        Some(cmd) => cmd,
        None => return Ok(None), // Not a valid applet, fall back to normal epkg operation
    };

    // Parse arguments using the applet's command structure
    // Clap expects the command name as the first argument, so prepend the applet name
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    args.insert(0, applet_name.clone());

    // Try to parse arguments - handle help requests specially
    let matches = match applet_cmd.clone().try_get_matches_from(args) {
        Ok(m) => m,
        Err(e) => {
            // If it's a help request or display help error, print it and exit
            if e.kind() == clap::error::ErrorKind::DisplayHelp ||
               e.kind() == clap::error::ErrorKind::DisplayHelpOnMissingArgumentOrSubcommand {
                e.print().expect("Failed to print help");
                std::process::exit(0);
            }
            // For other errors, return them as-is so clap can format them properly
            e.print().expect("Failed to print error");
            std::process::exit(2);
        }
    };

    // Execute the applet
    exec_builtin_command(&applet_name, &matches)?;

    Ok(Some(()))
}
