use clap::Command;
use color_eyre::Result;
use color_eyre::eyre::eyre;
use color_eyre::eyre::Context;
use std::io::IsTerminal;
use std::path::Path;
use std::sync::OnceLock;
use crate::models::PackageFormat;
use crate::utils::force_symlink_to_file;
use crate::utils::handle_clap_error_with_cmdline;
use pathdiff;
// Module declarations - these are auto-generated by build.rs
// To add a new applet, just create the .rs file in this directory
// The build script will automatically discover it and generate the declarations
// This file is generated in src/busybox/ so modules can be found
include!("_modules_gen.rs");

// Applet invocation patterns:
// 1. Direct symlink: ln -s /path/to/epkg whoami && ./whoami
// 2. Via busybox multicall: epkg busybox whoami
// 3. NOT: epkg whoami (epkg itself doesn't have subcommands)
// The handle_applet_invocation() function implements this logic.

/// Macro to register applet commands
/// Auto-generated from busybox directory at build time
macro_rules! register_busybox_applets {
    ($( $(#[$cfg:meta])* ($module:ident, $cmd_name:literal) ),* $(,)?) => {
        static APPLETS: OnceLock<Vec<Command>> = OnceLock::new();

        /// Get all busybox subcommands
        pub fn busybox_subcommands() -> &'static [Command] {
            APPLETS.get_or_init(|| vec![
                $( $(#[$cfg])* $module::command(), )*
            ])
        }

        /// Execute a built-in command by name and matches
        /// Returns an error if the command is not a built-in command
        pub fn exec_builtin_command(cmd_name: &str, matches: &clap::ArgMatches) -> Result<()> {
            match cmd_name {
                $(
                    $(#[$cfg])*
                    $cmd_name => {
                        let options = $module::parse_options(matches)?;
                        $module::run(options)
                    }
                )*
                _ => {
                    Err(eyre!("Unknown built-in command: {}", cmd_name))
                }
            }
        }
    };
}

// Include auto-generated registrations
// This file is generated by build.rs from files in src/busybox/
// It includes LINUX_ONLY_APPLETS, UNIX_ONLY_APPLETS, and register_busybox_applets! macro
include!(concat!(env!("OUT_DIR"), "/busybox_modules.rs"));

/// System administration commands that go in sbin instead of bin.
const SBIN_COMMANDS: &[&str] = &[
    "useradd", "userdel", "usermod", "groupadd", "groupdel",
    "adduser", "addgroup", "deluser", "delgroup",
    "ifconfig", "route", "mount", "umount",
];

/// Get applet names for a target platform.
///
/// This returns the list of applets that should be symlinked in the target environment,
/// based on the package format and whether the target is Linux/Unix.
///
/// - Linux-format packages (deb/rpm/apk/arch-linux): all applets including Linux-only
/// - Unix-like targets (macOS, etc.): Unix + common applets
/// - Windows-native targets (conda/brew/msys2 on Windows): only common applets
pub fn get_applet_names_for_target(pkg_format: &PackageFormat) -> Vec<String> {
    let mut applets = Vec::new();

    // Check if this is a Linux-format package that runs in VM on non-Linux hosts
    let is_linux_target = matches!(pkg_format,
        PackageFormat::Deb | PackageFormat::Rpm | PackageFormat::Apk);

    // For Arch Linux (not MSYS2), it's also a Linux target
    let is_arch_linux = *pkg_format == PackageFormat::Pacman &&
        crate::models::channel_config().distro != "msys2";

    let is_unix_target = is_linux_target || is_arch_linux;

    // Add all common applets (available on all platforms)
    applets.extend(COMMON_APPLETS.iter().map(|s| s.to_string()));

    // Add Unix-only applets for Unix targets
    if is_unix_target {
        for applet in UNIX_ONLY_APPLETS {
            if !applets.contains(&applet.to_string()) {
                applets.push(applet.to_string());
            }
        }
    }

    // Add Linux-only applets for Linux targets
    if is_linux_target || is_arch_linux {
        for applet in LINUX_ONLY_APPLETS {
            if !applets.contains(&applet.to_string()) {
                applets.push(applet.to_string());
            }
        }
    }

    applets.sort();
    applets
}

/// Get all applet names sorted alphabetically
pub fn sorted_applet_names() -> Vec<String> {
    let mut names: Vec<String> = busybox_subcommands()
        .iter()
        .map(|cmd| cmd.get_name().to_string())
        .collect();
    names.sort();
    names
}

/// Terminal width in columns when stdout is a TTY; 0 otherwise (caller should use 1 column, like upstream ls).
pub fn terminal_width() -> usize {
    if !std::io::stdout().is_terminal() {
        return 0;
    }
    let cols = console::Term::stdout().size().1;
    if cols > 0 { cols as usize } else { 0 }
}

// Compact output helpers: both use (items, widths, term_width). Flow = comma-separated wrap; columns = ls-style grid.

/// Format a list of strings into column layout (column-major order, padded to fit term width).
/// Uses per-column widths (like GNU ls) so more columns fit; each column is as wide as its longest entry.
/// When term_width is 0 (not a TTY), uses 1 column (one entry per line), matching upstream ls.
pub fn format_list_columns(items: &[String], widths: &[usize], term_width: usize) -> String {
    if items.is_empty() {
        return String::new();
    }
    let n_items = items.len();
    let max_w = widths.iter().copied().max().unwrap_or(0);

    let (n_cols, col_widths) = if term_width == 0 {
        (1, vec![max_w])
    } else {
        // Find largest n_cols such that sum(per-column max widths) + (n_cols-1)*2 (gaps) <= term_width
        const GAP: usize = 2;
        let mut best_n_cols = 1;
        let mut best_col_widths = vec![max_w];

        for n_cols_candidate in 1..=n_items {
            let n_rows = (n_items + n_cols_candidate - 1) / n_cols_candidate;
            let mut cw: Vec<usize> = vec![0; n_cols_candidate];
            for c in 0..n_cols_candidate {
                for r in 0..n_rows {
                    let idx = r + c * n_rows;
                    if idx < n_items {
                        cw[c] = cw[c].max(widths[idx]);
                    }
                }
            }
            let total = cw.iter().sum::<usize>() + n_cols_candidate.saturating_sub(1) * GAP;
            if total <= term_width {
                best_n_cols = n_cols_candidate;
                best_col_widths = cw;
            } else {
                break;
            }
        }
        (best_n_cols, best_col_widths)
    };

    let n_rows = (n_items + n_cols - 1) / n_cols;
    let mut out = String::new();
    for row in 0..n_rows {
        for c in 0..n_cols {
            let idx = row + c * n_rows;
            if idx >= n_items {
                break;
            }
            let s = &items[idx];
            let w = widths[idx];
            out.push_str(s);
            let padding = col_widths[c].saturating_sub(w);
            for _ in 0..padding {
                out.push(' ');
            }
            if c + 1 < n_cols {
                out.push_str("  ");
            }
        }
        if row + 1 < n_rows {
            out.push('\n');
        }
    }
    out
}

/// Format a list of strings in flow style: comma-separated, wrapping at term_width with indent on new lines.
/// Used for help text (e.g. applet list). `widths` are visible widths of each item.
/// If trailing_comma is true, each line ends with a comma (upstream busybox style).
fn format_list_compact_flow(
    items: &[String],
    widths: &[usize],
    term_width: usize,
    separator: &str,
    indent: &str,
    trailing_comma: bool,
) -> String {
    if items.is_empty() {
        return String::new();
    }
    let comma_extra = if trailing_comma { 1 } else { 0 };
    let mut result = String::new();
    let mut line = String::new();
    let mut line_display_len = 0usize;

    for (i, item) in items.iter().enumerate() {
        let need_sep = i > 0;
        let needed = if need_sep { separator.len() + widths[i] } else { widths[i] };

        if line.is_empty() {
            line.push_str(indent);
            line.push_str(item);
            line_display_len = indent.len() + widths[i];
        } else if term_width > 0 && line_display_len + comma_extra + needed <= term_width {
            line.push_str(separator);
            line.push_str(item);
            line_display_len += needed;
        } else {
            result.push_str(&line);
            if trailing_comma {
                result.push(',');
            }
            result.push('\n');
            line.clear();
            line.push_str(indent);
            line.push_str(item);
            line_display_len = indent.len() + widths[i];
        }
    }

    if !line.is_empty() {
        result.push_str(&line);
        if trailing_comma {
            result.push(',');
        }
        result.push('\n');
    }
    result
}

/// Visible character width of a string, ignoring ANSI escape sequences.
pub fn visible_width_ansi(s: &str) -> usize {
    let mut len = 0;
    let mut i = 0;
    let b = s.as_bytes();
    while i < b.len() {
        if b[i] == 0x1b && i + 1 < b.len() && b[i + 1] == b'[' {
            i += 2;
            while i < b.len() && b[i] != b'm' {
                i += 1;
            }
            if i < b.len() {
                i += 1;
            }
            continue;
        }
        len += 1;
        i += 1;
    }
    len
}

/// Format applet names into compact lines wrapped at given width (flow style: comma-separated).
/// Each line ends with a trailing comma to match upstream busybox.
pub fn format_applet_list_compact(width: usize) -> String {
    let names = sorted_applet_names();
    if names.is_empty() {
        return String::new();
    }
    let widths: Vec<usize> = names.iter().map(|s| s.len()).collect();
    format_list_compact_flow(&names, &widths, width, ", ", "    ", true)
}

/// Extract UID, GID, and mode bits from a reference file
///
/// This is used by chgrp, chmod, and chown applets to implement
/// the `--reference RFILE` flag. Returns an error if the file
/// cannot be accessed or metadata cannot be retrieved.
#[cfg(unix)]
pub fn extract_reference_metadata(_ref_path: &Path) -> Result<(u32, u32, u32)> {
    use std::os::unix::fs::MetadataExt;
    let metadata = std::fs::metadata(_ref_path)
        .map_err(|e| eyre!("cannot stat '{}': {}", _ref_path.display(), e))?;
    let uid = metadata.uid();
    let gid = metadata.gid();
    let mode = metadata.mode() & 0o7777;
    Ok((uid, gid, mode))
}

#[cfg(windows)]
fn strip_windows_exe_suffix(name: String) -> String {
    if name.len() > 4 && name[name.len() - 4..].eq_ignore_ascii_case(".exe") {
        name[..name.len() - 4].to_string()
    } else {
        name
    }
}

#[cfg(not(windows))]
fn strip_windows_exe_suffix(name: String) -> String {
    name
}

/// Get the applet name from the invocation (if any)
/// Returns None if not invoked as an applet
fn get_applet_name_from_invocation() -> Option<String> {
    let args: Vec<String> = std::env::args_os()
        .map(|a| a.to_string_lossy().into_owned())
        .collect();
    if args.is_empty() {
        return None;
    }

    // Get the program name as invoked (first argument)
    let invoked_name = &args[0];

    // Extract basename (handle both "/usr/bin/wget" and "wget")
    let applet_name = std::path::Path::new(invoked_name)
        .file_name()
        .and_then(|n| n.to_str())
        .map(|s| s.to_string());

    let applet_name = match applet_name {
        Some(name) => name,
        None => return None,
    };

    let applet_name = strip_windows_exe_suffix(applet_name);

    // Don't treat "epkg" itself as an applet
    if applet_name == "epkg" {
        return None;
    }

    Some(applet_name)
}

/// Returns true if the binary was invoked as a registered applet (e.g. symlink named "rpm").
pub fn is_invoked_as_applet() -> bool {
    let invoked = match get_applet_name_from_invocation() {
        Some(name) => name,
        None => return false,
    };
    let (applet_name, _) = if invoked == "[" {
        ("test".to_string(), true)
    } else {
        (invoked, false)
    };
    busybox_subcommands().iter().any(|cmd| cmd.get_name() == applet_name)
}

/// Handle applet invocation - parse arguments and execute the applet
/// Returns Ok(Some(())) if handled as an applet, Ok(None) if not an applet, Err on error
pub fn handle_applet_invocation() -> Result<Option<()>> {
    let invoked_applet_name = match get_applet_name_from_invocation() {
        Some(name) => name,
        None => return Ok(None), // Not invoked as an applet
    };

    // Normalize special invocation aliases.
    //
    // POSIX `[` is typically a synonym for `test` and is invoked as:
    //   [ expression ]
    // so we also strip a trailing `]` argument below.
    let (applet_name, strip_trailing_bracket) = if invoked_applet_name == "[" {
        ("test".to_string(), true)
    } else {
        (invoked_applet_name, false)
    };

    // Handle busybox multicall invocation: busybox <applet> [args...]
    let (applet_name, args_skip) = if applet_name == "busybox" {
        let mut args: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();
        if args.is_empty() {
            // No applet specified, fall back to normal epkg operation
            return Ok(None);
        }
        let real_applet = args.remove(0).to_string_lossy().into_owned();
        (real_applet, 2) // skip both "busybox" and the applet name
    } else {
        (applet_name, 1) // skip only the program name
    };

    // Get all applet commands and find the matching one in a single pass
    let applet_commands = busybox_subcommands();
    let applet_cmd = match applet_commands.iter()
        .find(|cmd| cmd.get_name() == applet_name) {
        Some(cmd) => cmd,
        None => return Ok(None), // Not a valid applet, fall back to normal epkg operation
    };

    // Parse arguments using the applet's command structure.
    // Pass raw OsString so path args (e.g. touch) keep bytes that are not valid UTF-8.
    let mut args: Vec<std::ffi::OsString> = std::env::args_os().skip(args_skip).collect();
    if strip_trailing_bracket && args.last().is_some_and(|a| a == std::ffi::OsStr::new("]")) {
        args.pop();
    }
    args.insert(0, std::ffi::OsString::from(applet_name.as_str()));

    // dpkg-maintscript-helper is called from maintscripts as: helper rm_conffile ... -- "$1" "$2" ...
    // Clap treats "--" as end of options and drops following args for the positional, so script
    // args (e.g. "install") would be lost. Run from raw argv so "--" and script args are preserved.
    #[cfg(target_os = "linux")]
    if applet_name == "dpkg-maintscript-helper" {
        let options = crate::busybox::dpkg_maintscript_helper::options_from_raw_args(&args[1..]);
        crate::busybox::dpkg_maintscript_helper::run(options)?;
        return Ok(Some(()));
    }

    // Try to parse arguments - handle help requests specially
    let cmdline = args.iter().map(|a| a.to_string_lossy()).collect::<Vec<_>>().join(" ");
    let matches = match applet_cmd.clone().try_get_matches_from(args) {
        Ok(matches) => matches,
        Err(e) => handle_clap_error_with_cmdline(e, cmdline),
    };

    // Execute the applet
    exec_builtin_command(&applet_name, &matches)?;

    Ok(Some(()))
}

/// Determine if a command should be placed in sbin (system administration) or bin (user commands)
fn is_sbin_command(cmd_name: &str) -> bool {
    SBIN_COMMANDS.contains(&cmd_name)
}

/// Return true when this epkg binary is built for a musl environment.
///
/// All current static builds use musl, so for APK environments we only create
/// applet symlinks when this returns true.
#[cfg(unix)]
fn is_musl_build() -> bool {
    #[cfg(target_env = "musl")]
    {
        true
    }
    #[cfg(not(target_env = "musl"))]
    {
        false
    }
}

/// Determine which epkg binary to use for applet symlinks.
///
/// On Windows/macOS hosts:
/// - For Linux-format packages (deb/rpm/arch/apk): use epkg-linux-$arch for VM execution
/// - For native formats (conda/brew/msys2): use native epkg
///
/// On Linux hosts: always use native epkg
///
/// Returns None if the appropriate binary is not found (e.g., epkg-linux-$arch missing for VM env)
fn determine_epkg_binary_for_env(env_root: &Path, pkg_format: &PackageFormat) -> Option<std::path::PathBuf> {
    // Check if this is a Linux-format package that requires VM on non-Linux hosts
    #[cfg(not(target_os = "linux"))]
    {
        let needs_vm = matches!(pkg_format,
            PackageFormat::Deb | PackageFormat::Rpm | PackageFormat::Apk
        );

        // For Arch Linux (not MSYS2), we need VM
        let is_arch_linux = *pkg_format == PackageFormat::Pacman &&
            crate::models::channel_config().distro != "msys2";

        if needs_vm || is_arch_linux {
            // First check if 'epkg' symlink exists in target env - prefer it for simpler relative paths
            let epkg_symlink = crate::dirs::path_join(env_root, &["usr", "bin", crate::dirs::EPKG_USR_BIN_NAME]);
            if epkg_symlink.exists() {
                log::debug!("Using epkg symlink from target env: {}", epkg_symlink.display());
                return Some(epkg_symlink);
            }

            // Fallback: check epkg-linux-$arch in target env, then in self env
            let arch = &crate::config().common.arch;
            let epkg_linux = crate::dirs::path_join(env_root, &["usr", "bin", &format!("epkg-linux-{}", arch)]);
            if epkg_linux.exists() {
                log::debug!("Using epkg-linux binary from target env: {}", epkg_linux.display());
                return Some(epkg_linux);
            }

            // Check in self environment
            let self_env = crate::dirs().user_envs.join("self");
            let self_epkg_linux = crate::dirs::path_join(&self_env, &["usr", "bin", &format!("epkg-linux-{}", arch)]);
            if self_epkg_linux.exists() {
                log::debug!("Using epkg-linux binary from self env: {}", self_epkg_linux.display());
                return Some(self_epkg_linux);
            }

            log::debug!("epkg-linux-{} not found in target env or self env, skipping applet symlinks", arch);
            return None;
        }
    }

    // Silence unused warning on Linux
    #[cfg(target_os = "linux")]
    let _ = pkg_format;

    // Default: use native epkg binary
    let epkg_exe = crate::dirs::path_join(env_root, &["usr", "bin", crate::dirs::EPKG_USR_BIN_NAME]);
    if epkg_exe.exists() {
        log::debug!("Using native epkg binary at {}", epkg_exe.display());
        Some(epkg_exe)
    } else {
        let current_exe = std::env::current_exe().ok();
        if let Some(exe) = &current_exe {
            log::debug!("Using current executable at {}", exe.display());
        }
        current_exe
    }
}

/// Create symlinks for all registered applets in the environment
/// This automatically discovers all applets and places them in the appropriate directory (bin or sbin)
pub fn create_all_applet_symlinks(env_root: &Path, pkg_format: &PackageFormat) -> Result<()> {
    log::debug!("Creating busybox applet links for format {:?}", pkg_format);

    // Determine which epkg binary to use for applet symlinks
    // On Windows/macOS with Linux-format packages, use epkg-linux-$arch for VM execution
    let epkg_exe = match determine_epkg_binary_for_env(env_root, pkg_format) {
        Some(exe) => exe,
        None => {
            log::debug!("No suitable epkg binary found, skipping applet symlinks");
            return Ok(());
        }
    };

    // On Alpine (APK format) with a glibc-linked epkg binary, the binary will
    // not run at all. All static builds currently use musl, so only create
    // applet symlinks when building for musl; otherwise return early.
    #[cfg(unix)]
    if *pkg_format == PackageFormat::Apk && !is_musl_build() {
        return Ok(());
    }

    // Determine if the target environment is Windows-based (needs .exe suffix).
    // For Linux-format packages, never add .exe suffix even on Windows host.
    fn is_windows_target(pkg_format: &PackageFormat) -> bool {
        match pkg_format {
            PackageFormat::Deb | PackageFormat::Rpm | PackageFormat::Apk => false,
            PackageFormat::Pacman => crate::models::channel_config().distro == "msys2",
            PackageFormat::Conda | PackageFormat::Brew | PackageFormat::Python | PackageFormat::Epkg => {
                #[cfg(windows)]
                { true }
                #[cfg(not(windows))]
                { false }
            }
        }
    }

    fn applet_symlink_filename(cmd_name: &str, pkg_format: &PackageFormat) -> String {
        if is_windows_target(pkg_format) {
            format!("{}.exe", cmd_name)
        } else {
            cmd_name.to_string()
        }
    }

    // Get applet names based on target platform, not the running epkg's built-in applets
    let applet_names = get_applet_names_for_target(pkg_format);
    for cmd_name in &applet_names {
        let subdir = if is_sbin_command(cmd_name) { "sbin" } else { "bin" };
        let symlink_path = env_root.join("usr").join(subdir).join(applet_symlink_filename(cmd_name, pkg_format));
        let target = if let Some(parent) = symlink_path.parent() {
            pathdiff::diff_paths(&epkg_exe, parent).unwrap_or(epkg_exe.clone())
        } else {
            epkg_exe.clone()
        };
        force_symlink_to_file(&target, &symlink_path)
            .with_context(|| format!("Failed to create {} symlink in {}", cmd_name, symlink_path.display()))?;
    }
    // Create [ symlink (alias for test)
    let bracket_leaf = applet_symlink_filename("[", pkg_format);
    let bracket_path = crate::dirs::path_join(env_root, &["usr", "bin", &bracket_leaf]);
    let bracket_target = if let Some(parent) = bracket_path.parent() {
        pathdiff::diff_paths(&epkg_exe, parent).unwrap_or(epkg_exe.clone())
    } else {
        epkg_exe.clone()
    };
    force_symlink_to_file(&bracket_target, &bracket_path)?;
    Ok(())
}
